"""Dati delle mappe: griglie ASCII, legenda, trigger, NPC.

Legenda trigger:
  on: "enter" (calpestando la cella) | "interact" (SPAZIO sulla cella o di fronte)
  event: id evento in game/story.py       once: consumato per sempre (in state.done)
  requires_flag / unless_flag: condizioni  locked_event: evento se il transfer è chiuso
  transfer: [mappa, x, y, facing]          chest: [item_id, qty]
  battle: id battaglia (anomalia)          savepoint: True
  glyph: solo cosmetico (l'evento fa il resto)
"""

LEGEND = {
    ".": {},
    ",": {"floor": "floor_ship_b"},
    "_": {"floor": "floor_hall"},
    "#": {"tile": "wall_ship", "solid": True, "no_floor": True},
    "^": {"tile": "wall_ship_top", "solid": True, "no_floor": True},
    "~": {"tile": "window_star", "solid": True, "no_floor": True},
    "c": {"tile": "console", "solid": True},
    "C": {"tile": "console_glow", "solid": True},
    "k": {"tile": "crate", "solid": True},
    "b": {"tile": "barrel", "solid": True},
    "B": {"tile": "bed", "solid": True},
    "t": {"tile": "table", "solid": True},
    "h": {"tile": "chair"},
    "l": {"tile": "locker", "solid": True},
    "p": {"tile": "plant_pot", "solid": True},
    "i": {"tile": "pipe", "solid": True},
    "v": {"tile": "vent"},
    "H": {"tile": "hatch"},
    "q": {"tile": "planter_a", "solid": True},
    "Q": {"tile": "planter_b", "solid": True},
    "Y": {"tile": "tree_glow", "solid": True},
    "P": {"tile": "pillar", "solid": True, "no_floor": True},
    "r": {"tile": "rubble"},
    "x": {"tile": "crystal_a", "solid": True},
    "X": {"tile": "crystal_b", "solid": True},
    "G": {"tile": "glyph_wall", "solid": True, "no_floor": True},
    "g": {"tile": "glyph_floor"},
    "a": {"tile": "altar", "solid": True},
    "S": {"tile": "savepoint"},
    "K": {"tile": "chest_closed", "solid": True},
    "T": {"tile": "terminal_story", "solid": True},
    "E": {"tile": "elevator"},
    "D": {"tile": "door_open"},
    "A": {"tile": "anomaly"},
    "*": {"tile": "glyph_floor"},
}

MAPS = {
    # ================================================== PONTE HABITAT ====
    "habitat": {
        "name": "Auriga — Ponte Habitat",
        "music": "explore",
        "floor": "floor_ship_a",
        "auto": [{"id": "habitat_intro", "event": "ev_intro", "once": True}],
        "rows": [
            "####################################",
            "#.B.....#..l........#.....t........#",
            "#.......#.B.....B...#....th....T...#",
            "#.K.....#...........#..............#",
            "#.......#...........#.....p........#",
            "#.......#...........#............K.#",
            "#.......#...........#..............#",
            "#.......#...........#..............#",
            "####.#########.############.########",
            "#__________________________________#",
            "#__S_______________________________#",
            "#__________________________________#",
            "########.#############GGGGGGG######",
            "#..............#...................#",
            "#..............#...................#",
            "#kk.b..........#...................#",
            "#..............#..................D",
            "#..................................#",
            "#..............#...................#",
            "#.........A....#...................#",
            "#..............#...................#",
            "####################################",
        ],
        "entities": [
            {"name": "Ada", "sheet": "npc_ada", "x": 12, "y": 3, "facing": "down",
             "event": "ev_ada"},
            {"name": "Luce", "sheet": "npc_luce", "x": 28, "y": 4, "facing": "down",
             "event": "ev_luce"},
            {"name": "Ilan", "sheet": "ilan", "x": 25, "y": 13, "facing": "up",
             "event": "ev_ilan_join", "hidden_flag": "ilan_joined"},
        ],
        "triggers": [
            {"id": "hab_save", "x": 3, "y": 10, "on": "interact", "savepoint": True},
            {"id": "hab_chest1", "x": 2, "y": 3, "on": "interact", "once": True,
             "chest": ["razione", 2]},
            {"id": "hab_chest2", "x": 33, "y": 5, "on": "interact", "once": True,
             "chest": ["cella", 2]},
            {"id": "hab_diario", "x": 31, "y": 2, "on": "interact",
             "event": "ev_diario"},
            {"id": "hab_glifi", "x": 25, "y": 12, "on": "interact",
             "event": "ev_muro_glifi"},
            {"id": "hab_anomalia", "x": 10, "y": 19, "on": "enter", "once": True,
             "battle": "b_anomalia_hab"},
            {"id": "hab_letto", "x": 2, "y": 1, "on": "interact",
             "event": "ev_letto"},
            {"id": "hab_pianta", "x": 26, "y": 4, "on": "interact",
             "event": "ev_pianta"},
            {"id": "hab_to_off", "x": 34, "y": 16, "on": "enter",
             "transfer": ["officina", 1, 10, "right"],
             "requires_flag": "hab_door_open", "locked_event": "ev_porta_bloccata"},
        ],
    },

    # ====================================================== OFFICINA ====
    "officina": {
        "name": "Auriga — Officina di Poppa",
        "music": "explore",
        "floor": "floor_ship_b",
        "auto": [{"id": "off_intro", "event": "ev_officina_intro", "once": True}],
        "rows": [
            "######################################",
            "#iiiiiii......................iiiiiii#",
            "#....................................#",
            "#kk................................K.#",
            "#....................................#",
            "#...............^^^^^^...............#",
            "#...............^..C.^...............#",
            "#...............^^..^^...............#",
            "#....................................#",
            "#....................................#",
            "D....................................#",
            "#....................................#",
            "#...........................A........#",
            "#bb..................................#",
            "#....................................#",
            "#........kkk.........................#",
            "#....................................#",
            "#...S................................#",
            "#..................................E.#",
            "#....................................#",
            "#v..................................v#",
            "######################################",
        ],
        "entities": [
            {"name": "Bruno", "sheet": "npc_bruno", "x": 8, "y": 8, "facing": "down",
             "event": "ev_bruno"},
            {"name": "Sette", "sheet": "sette", "x": 18, "y": 6, "facing": "down",
             "event": "ev_sette_join", "hidden_flag": "sette_joined"},
        ],
        "triggers": [
            {"id": "off_save", "x": 4, "y": 17, "on": "interact", "savepoint": True},
            {"id": "off_chest", "x": 35, "y": 3, "on": "interact", "once": True,
             "chest": ["gel", 2]},
            {"id": "off_anomalia", "x": 28, "y": 12, "on": "enter", "once": True,
             "battle": "b_anomalia_off"},
            {"id": "off_casse", "x": 10, "y": 15, "on": "interact",
             "event": "ev_casse"},
            {"id": "off_barile", "x": 1, "y": 13, "on": "interact",
             "event": "ev_barile"},
            {"id": "off_to_hab", "x": 0, "y": 10, "on": "enter",
             "transfer": ["habitat", 33, 16, "left"]},
            {"id": "off_to_idro", "x": 35, "y": 18, "on": "enter",
             "transfer": ["idroponica", 3, 2, "right"],
             "requires_flag": "ascensore_aperto",
             "locked_event": "ev_ascensore_bloccato"},
        ],
    },

    # =============================================== ANELLO IDROPONICO ==
    "idroponica": {
        "name": "Auriga — Anello Idroponico",
        "music": "hydro",
        "floor": "floor_hydro",
        "auto": [{"id": "idro_intro", "event": "ev_idro_intro", "once": True}],
        "rows": [
            "##################~~~~##################",
            "#......................................#",
            "#.E..................................K.#",
            "#......................................#",
            "#qqqqq...qqqqq...qqqqq...qqqqq...qqqqq.#",
            "#QQQQQ...QQQQQ...QQQQQ...QQQQQ...QQQQQ.#",
            "#......................................#",
            "#......................................#",
            "#...........A..............A...........#",
            "#qqqqqqqqqqqqqqqqqq.qqqqqqqqqqqqqqqqqqq#",
            "#......................................#",
            "#.................YY...................#",
            "#......................................D",
            "#......................................#",
            "#....T.................................#",
            "#......................................#",
            "#qqqqq...qqqqq...qqqqq...qqqqq...qqqqq.#",
            "#QQQQQ...QQQQQ...QQQQQ...QQQQQ...QQQQQ.#",
            "#......................................#",
            "#......................................#",
            "#...S..................................#",
            "#....................................K.#",
            "#......................................#",
            "########################################",
        ],
        "entities": [
            {"name": "Naia", "sheet": "naia", "x": 18, "y": 12, "facing": "up",
             "event": "ev_naia_chat", "hidden_flag": "naia_joined"},
        ],
        "triggers": [
            {"id": "idro_save", "x": 4, "y": 20, "on": "interact", "savepoint": True},
            {"id": "idro_chest1", "x": 37, "y": 2, "on": "interact", "once": True,
             "chest": ["stimolante", 1]},
            {"id": "idro_chest2", "x": 37, "y": 21, "on": "interact", "once": True,
             "chest": ["fiala_luce", 1]},
            {"id": "idro_anom1", "x": 12, "y": 8, "on": "enter", "once": True,
             "battle": "b_anomalia_idro"},
            {"id": "idro_anom2", "x": 27, "y": 8, "on": "enter", "once": True,
             "battle": "b_spore1"},
            {"id": "idro_imboscata", "x": 19, "y": 9, "on": "enter", "once": True,
             "event": "ev_imboscata_spore"},
            {"id": "idro_albero", "x": 18, "y": 11, "on": "interact",
             "event": "ev_albero"},
            {"id": "idro_finestra", "x": 19, "y": 0, "on": "interact",
             "event": "ev_finestra"},
            {"id": "idro_glifo", "x": 5, "y": 14, "on": "interact",
             "event": "ev_glifo_idro"},
            {"id": "idro_to_off", "x": 2, "y": 2, "on": "enter",
             "transfer": ["officina", 34, 18, "left"]},
            {"id": "idro_to_cuore", "x": 39, "y": 12, "on": "enter",
             "transfer": ["cuore", 1, 2, "right"],
             "requires_flag": "idro_glifo", "locked_event": "ev_porta_cuore"},
        ],
    },

    # ============================================= IL CUORE (ROVINE) ====
    "cuore": {
        "name": "Il Cuore — Rovine dei Tessitori",
        "music": "ruins",
        "floor": "floor_ruin_a",
        "auto": [{"id": "cuore_intro", "event": "ev_rovine_intro", "once": True}],
        "rows": [
            "##########################################",
            "#........................................#",
            "D........................................#",
            "#........................................#",
            "#..P....x...P....r....X...P....x....P....#",
            "#........................................#",
            "#.................................*......#",
            "#........................................#",
            "#.......*................................#",
            "#........................................#",
            "#GGGGGGGGGGGGGGGGGGGG.GGGGGGGGGGGGGGGGGGG#",
            "#........................................#",
            "#....A...................................#",
            "#........................................#",
            "#....x.......r.......X.......r......x....#",
            "#........................................#",
            "#...................*....................#",
            "#........................................#",
            "#PPPPPPPPPPPPPPPPPPP..PPPPPPPPPPPPPPPPPPP#",
            "#.............................A..........#",
            "#....................S...................#",
            "#........................................#",
            "#...................a....................#",
            "#........................................#",
            "#........................................#",
            "##########################################",
        ],
        "entities": [],
        "triggers": [
            {"id": "cuore_save", "x": 21, "y": 20, "on": "interact", "savepoint": True},
            {"id": "cuore_anom1", "x": 5, "y": 12, "on": "enter", "once": True,
             "battle": "b_anomalia_cuore"},
            {"id": "cuore_anom2", "x": 30, "y": 19, "on": "enter", "once": True,
             "battle": "b_rovine1"},
            {"id": "cuore_g1", "x": 8, "y": 8, "on": "enter", "once": True,
             "event": "ev_glifo1"},
            {"id": "cuore_g2", "x": 20, "y": 16, "on": "enter", "once": True,
             "event": "ev_glifo2"},
            {"id": "cuore_g3", "x": 34, "y": 6, "on": "enter", "once": True,
             "event": "ev_glifo3"},
            {"id": "cuore_sentinella", "x": 21, "y": 11, "on": "enter", "once": True,
             "event": "ev_sentinella"},
            {"id": "cuore_altare", "x": 20, "y": 22, "on": "interact",
             "event": "ev_altare"},
            {"id": "cuore_cristallo", "x": 5, "y": 14, "on": "interact",
             "event": "ev_cristallo"},
            {"id": "cuore_to_idro", "x": 0, "y": 2, "on": "enter",
             "transfer": ["idroponica", 38, 12, "left"]},
        ],
    },
}
